FROM node:18-slim AS CLIENT_BUILD

WORKDIR /app

COPY frontend .

RUN yarn install 

RUN REACT_APP_BASE_URL=https://teamtasker.in yarn run build

FROM node:18-slim

WORKDIR /app

COPY --from=CLIENT_BUILD /app/build ./client/build

COPY api .

RUN yarn install

EXPOSE 5000

CMD ["/bin/sh", "-c", "entrypoint.sh"]