# Stage 1: Building client build
FROM node:18 as frontend-builder

RUN apt-get update

WORKDIR /frontend
COPY frontend /frontend
RUN yarn run build

# Stage 2: Final image
FROM node:18

RUN apt-get update

WORKDIR /app

COPY --from=frontend-builder /frontend/build ./client
COPY api ./api

RUN yarn install

ENV APP_PORT=5000

CMD yarn run server