name: Build and Deploy TeamTasker
on:
  push:
    branches:
      - master
    paths:
      - 'api/**'
      - 'frontend/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build docker image
        run: docker-compose build
      
      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Push to docker hub
        run: docker-compose push

  copy-compose-to-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy Docker Compose file to EC2
        uses: appleboy/scp-action@v0.1.7 # https://github.com/appleboy/scp-action
        with:
          host: ${{ secrets.TT_HOST }}
          username: ${{ secrets.TT_USERNAME }}
          key: ${{ secrets.TT_SSHKEY }}
          source: compose.yml
          target: ~/

  deploy:
    runs-on: ubuntu-latest
    needs: 
      - copy-compose-to-ec2
      - build-and-push

    steps:
      - name: SSH to teamtasker instance
        uses: appleboy/ssh-action@v1.0.3 # https://github.com/appleboy/ssh-action
        with:
          host: ${{ secrets.TT_HOST }}
          username: ${{ secrets.TT_USERNAME }}
          key: ${{ secrets.TT_SSHKEY }}
          script: |
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            docker compose -f ~/compose.yml down --rmi all
            docker compose -f ~/compose.yml pull
            ${{ secrets.ENV_VARIABLES }} docker compose -f ~/compose.yml up -d
      
